name: Upgrade @howmuchgreen/howmuchcarbon
on:
  repository_dispatch:
    types:
      - upgrade-library
jobs:
  upgrade-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.HOWMUCHBOT_GH_TOKEN }}
      - name: Upgrade howmuchcarbon library
        run: npm add @howmuchgreen/howmuchcarbon@latest
      - name: Extract version number
        run: echo "::set-env name=LIB_VERSION::$(npm list @howmuchgreen/howmuchcarbon | grep -o '\d\.\d\.\d')"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: upgrading howmuchcarbon to v${{ env.LIB_VERSION }}"
